# Site settings
title: "LSF"
description: "Website for Lanka software foundation"
url: ""
version: v0.1.0

# Contact information
email: "contact@opensource.lk"
phone: "0703729895"
address: ""

# Social media
social:
  linkedin: "https://www.linkedin.com/company/lsflk/"
  github: "https://github.com/LSFLKß"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Collections
collections:
  datasets:
    output: true
    permalink: /:collection/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/


