# Site settings
title: "LSF"
description: "Website for Lanka software foundation"

# --- Important for GitHub Pages ---
# Sets the main domain for your site, required by plugins.
url: "https://maneeshayjw.github.io" 
# Sets the subdirectory of your site. Must be the name of your repository.
baseurl: "/lsf-web"
# ------------------------------------

version: v0.1.0

# Contact information
email: "contact@opensource.lk"
phone: "0703729895"
address: ""

# Social media
social:
  linkedin: "https://www.linkedin.com/company/lsflk/"
  github: "https://github.com/LSFLK" # Typo was fixed here


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Collections
collections:
  datasets:
    output: true
    permalink: /:collection/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Tells Jekyll to publish posts with dates set in the future.
# This is important because GitHub's servers are in a different timezone.
future: true